"""Generate a Vim colorscheme file from the extracted palette.

Produces a .vim file that works in both GUI Vim (guifg/guibg hex colors)
and terminal Vim (ctermfg/ctermbg xterm-256 indices).  The output covers
~180 highlight groups across:

  - Core UI:      Normal, Visual, Search, StatusLine, PMenu, Diff, Spell, …
  - Syntax:       Comment, String, Function, Keyword, Type, Operator, …
  - LSP:          DiagnosticError/Warn/Info/Hint + underline variants
  - Plugins:      NERDTree, Startify, Tagbar, CoC, Signify, BufTabLine
  - Git:          gitcommit*, diff*
  - Terminal:     g:terminal_color_{0..15} for Vim 8+ / Neovim

Every foreground color is contrast-checked against the background in
the extraction step (colors.py) to guarantee readability (WCAG ratio ≥ 3.0).
"""

import os

from .colors import extract_colors, clamp_hsv, to_hex, to_256


def _hi(group, fg=None, bg=None, attr=None, sp=None):
  """Build a Vim `:highlight` command string for a single group.

  Emits both gui (hex) and cterm (256-index) color attributes so the
  theme works in graphical Vim, terminal Vim, and Neovim alike.

  Args:
    group: Vim highlight group name (e.g. "Normal", "Comment").
    fg:    Foreground float-RGB tuple, or None for "NONE".
    bg:    Background float-RGB tuple, or None for "NONE".
    attr:  Font attribute string ("bold", "underline", "undercurl", "NONE").
    sp:    Special color for undercurl/underline (float-RGB), or None.

  Returns:
    A complete `:hi` command string (without leading colon).
  """
  # Convert float RGB to hex for gui and to 256-index for cterm
  gfg = to_hex(fg) if fg else "NONE"
  gbg = to_hex(bg) if bg else "NONE"
  cfg = str(to_256(fg)) if fg else "NONE"
  cbg = "NONE"  # ctermbg is always NONE — we let the terminal handle bg
  a   = attr or "NONE"
  line = "hi {} term=NONE guifg={} guibg={} ctermfg={} ctermbg={} gui={} cterm={}".format(
      group, gfg, gbg, cfg, cbg, a, a)
  # guisp is used for undercurl/underline color in GUI Vim
  if sp:
    line += " guisp={}".format(to_hex(sp))
  return line


def _link(group, target):
  """Build a Vim `:hi! link` command that aliases *group* to *target*.

  The `!` forces the link even if *group* was already defined.
  """
  return "hi! link {} {}".format(group, target)


def generate_vim(options):
  """Generate a Vim colorscheme file from the extracted palette.

  Pipeline:
    1. Extract the 8-color palette from the image.
    2. Derive semantic colors (bg, fg, comment, selection, error bg, etc.)
       from specific palette slots with HSV clamping.
    3. Unpack contrast-checked semantic colors from extraction.
    4. Build ~180 `:hi` commands organized by category.
    5. Append g:terminal_color_{0..15} variables for embedded terminals.
    6. Create parent directories if needed and write the .vim file.

  Args:
    options: argparse namespace with:
      .vim_out — output path for the .vim file
      (plus all color-tuning options forwarded to extract_colors)
  """
  palette, sem, _ = extract_colors(options)

  # -- Unpack pre-computed semantic colors from extraction ---------------
  bg        = sem['bg']
  bg2       = sem['bg2']
  fg        = sem['fg']
  comment   = sem['comment']
  sel       = sem['sel']
  red       = sem['red']
  red_b     = sem['red_b']
  green     = sem['green']
  green_b   = sem['green_b']
  yellow    = sem['yellow']
  yellow_b  = sem['yellow_b']
  blue      = sem['blue']
  blue_b    = sem['blue_b']
  magenta   = sem['magenta']
  magenta_b = sem['magenta_b']
  cyan      = sem['cyan']
  cyan_b    = sem['cyan_b']
  bold_col  = sem['bold']
  err_bg    = sem['err_bg']

  # Derive the colorscheme name from the output filename (without extension)
  name = os.path.splitext(os.path.basename(options.vim_out))[0]

  # Local aliases for readability in the highlight table below
  hi = _hi
  link = _link

  # -- Build highlight commands -----------------------------------------
  # Each section is a logical group of related highlight definitions.
  lines = [
    '" Generated by iterm-theme-generator',
    "set background=dark",
    "hi clear",
    "if exists('syntax_on') | syntax reset | endif",
    "let g:colors_name = '{}'".format(name),
    "",

    # ── UI elements ────────────────────────────────────────────────────
    '" ── UI ──────────────────────────────────────────────────────────────',
    hi("Normal",          fg=fg,      bg=None if getattr(options, 'vim_no_bg', False) else bg),       # Default text
    hi("NormalFloat",     fg=fg,      bg=bg2),      # Floating windows (Neovim)
    hi("NonText",         fg=comment),               # ~ lines after EOF, listchars
    hi("EndOfBuffer",     fg=comment),               # ~ column in Neovim
    hi("SpecialKey",      fg=comment),               # Unprintable characters
    hi("Conceal",         fg=comment),               # Concealed text (e.g. in markdown)
    hi("Visual",          fg=fg,      bg=sel),       # Visual selection
    hi("VisualNOS",       fg=fg,      bg=sel),       # Visual selection (not-owning)
    hi("Search",          fg=bg,      bg=yellow),    # Last search pattern highlight
    hi("IncSearch",       fg=bg,      bg=yellow_b),  # Incremental search match
    hi("CurSearch",       fg=bg,      bg=yellow_b),  # Current search match (Neovim)
    hi("MatchParen",      fg=bg,      bg=bold_col, attr="bold"),  # Matching bracket
    hi("Cursor",          fg=bg,      bg=fg),        # Cursor block
    hi("CursorLine",                               attr="NONE"),  # Line under cursor
    hi("CursorColumn",                             attr="NONE"),  # Column under cursor
    hi("CursorLineNr",    fg=yellow),                # Line number on cursor line
    hi("ColorColumn"),                               # Column guide (default)
    hi("LineNr",          fg=comment),               # Line numbers
    hi("SignColumn",      fg=green),                 # Gutter sign column
    hi("FoldColumn",      fg=comment),               # Fold indicator column
    hi("Folded",          fg=comment, bg=bg2),       # Folded text
    hi("VertSplit",       fg=comment),                # Vertical split separator
    hi("WinSeparator",    fg=comment),                # Window separator (Neovim)
    hi("StatusLine",      fg=fg,      bg=blue),      # Active status line
    hi("StatusLineNC",    fg=comment),               # Inactive status line
    hi("StatusLineTerm",  fg=fg,      bg=blue),      # Terminal status line
    hi("StatusLineTermNC",fg=comment),               # Inactive terminal status line
    hi("TabLine",         fg=comment,              attr="NONE"),  # Inactive tab
    hi("TabLineSel",      fg=fg,      bg=blue, attr="NONE"),     # Active tab
    hi("TabLineFill",                              attr="NONE"),  # Tab bar background
    hi("WildMenu",        fg=bg,      bg=cyan, attr="bold"),     # Wildmenu selection
    hi("PMenu",           fg=fg,      bg=bg2),       # Popup menu
    hi("PMenuSel",        fg=fg,      bg=sel),       # Popup menu selected item
    hi("PMenuSbar"),                                 # Popup scrollbar
    hi("PMenuThumb"),                                # Popup scrollbar thumb
    hi("Directory",       fg=blue),                  # Directory names in listings
    hi("Title",           fg=comment, attr="bold"),  # Titles in :set, :marks, etc.
    hi("ModeMsg",         fg=yellow),                # -- INSERT --, -- VISUAL --, etc.
    hi("MoreMsg",         fg=yellow),                # "-- More --" prompt
    hi("Question",        fg=yellow),                # Yes/no prompts
    hi("WarningMsg",      fg=magenta_b),             # Warning messages
    hi("Error",           fg=red_b,   bg=err_bg),    # Error messages
    hi("ErrorMsg",        fg=red_b,   bg=err_bg),    # Command-line error messages
    hi("Todo",            fg=yellow,               attr="bold"),  # TODO/FIXME/XXX
    hi("DiffAdd",         bg=clamp_hsv(green, maxs=0.5, minv=0.08, maxv=0.10)),
    hi("DiffChange",      bg=clamp_hsv(blue, maxs=0.5, minv=0.1, maxv=0.2)),
    hi("DiffDelete",      bg=clamp_hsv(red, maxs=0.5, minv=0.08, maxv=0.10)),
    hi("DiffText",        bg=clamp_hsv(blue, maxs=0.80, minv=0.12, maxv=0.22), attr="bold"),   # Changed text within a line
    hi("SpellBad",        sp=red,     attr="undercurl"),          # Misspelled word
    hi("SpellCap",        sp=blue,    attr="undercurl"),          # Uncapitalized sentence
    hi("SpellLocal",      sp=cyan,    attr="undercurl"),          # Wrong region word
    hi("SpellRare",       sp=magenta, attr="undercurl"),          # Rare word
    hi("IndentGuidesOdd"),                           # vim-indent-guides odd level
    hi("IndentGuidesEven"),                          # vim-indent-guides even level
    "",

    # ── Syntax highlighting ────────────────────────────────────────────
    '" ── Syntax ──────────────────────────────────────────────────────────',
    hi("Comment",         fg=comment),               # Code comments
    hi("SpecialComment",  fg=comment,              attr="bold"),  # Doc comments, shebangs
    link("pythonDocstring", "Comment"),               # Python docstrings (if syntax defines it)
    hi("pythonTripleQuotes", fg=comment),             # """ and ''' delimiters → comment color
    hi("Constant",        fg=cyan),                  # Generic constants
    hi("String",          fg=green),                 # String literals
    hi("Character",       fg=green),                 # Character literals
    hi("Number",          fg=cyan),                  # Numeric literals
    hi("Boolean",         fg=green,   attr="bold"),  # true/false
    hi("Float",           fg=cyan),                  # Floating-point literals
    hi("Identifier",      fg=blue),                  # Variable names
    hi("Function",        fg=fg),                    # Function/method names
    hi("Statement",       fg=magenta_b, attr="NONE"),  # Generic statements
    hi("Conditional",     fg=magenta,   attr="bold"),  # if/else/switch
    hi("Repeat",          fg=magenta,   attr="bold"),  # for/while/do
    hi("Label",           fg=blue),                  # case/default labels
    hi("Operator",        fg=cyan,    attr="NONE"),  # +, -, =, etc.
    hi("Keyword",         fg=blue),                  # Language keywords
    hi("Exception",       fg=red),                   # try/catch/throw
    hi("PreProc",         fg=blue),                  # Generic preprocessor
    hi("Include",         fg=red),                   # #include, import
    hi("Define",          fg=blue),                  # #define
    hi("Macro",           fg=blue),                  # Macro usage
    hi("PreCondit",       fg=cyan),                  # #if, #ifdef
    hi("Type",            fg=magenta_b, attr="bold"),  # Type names
    hi("StorageClass",    fg=blue,    attr="bold"),  # static, volatile, etc.
    hi("Structure",       fg=blue,    attr="bold"),  # struct, union, enum
    hi("Typedef",         fg=magenta_b, attr="bold"),  # typedef
    hi("Special",         fg=fg),                    # Special symbols
    hi("SpecialChar",     fg=fg),                    # Escape sequences
    hi("Tag",             fg=green),                 # Tags (HTML, ctags)
    hi("Delimiter",       fg=cyan),                  # Brackets, commas
    hi("Debug",           fg=cyan),                  # Debug statements
    hi("Underlined",      fg=blue,    attr="underline"),  # Hyperlinks in help
    hi("Ignore",          fg=comment),               # Hidden text
    hi("Global",          fg=blue),                  # Global scope markers
    "",

    # ── Diff highlighting ──────────────────────────────────────────────
    '" ── Diff ────────────────────────────────────────────────────────────',
    hi("diffAdded",       fg=green_b),                # Added lines
    hi("diffRemoved",     fg=clamp_hsv(red, maxs=0.6, maxv=0.55)),  # Removed lines
    hi("Added",           fg=green_b),                # Vim 9+ / Neovim Added group
    hi("Removed",         fg=clamp_hsv(red, maxs=0.6, maxv=0.55)),  # Vim 9+ / Neovim Removed group
    hi("diffFile",        fg=yellow,  attr="bold"),  # File header
    hi("diffNewFile",     fg=yellow),                # New file header
    hi("diffLine",        fg=blue,    attr="bold"),  # @@ line numbers
    hi("diffIndexLine",   fg=blue),                  # Index line
    hi("diffSubname",     fg=fg),                    # Function context
    hi("diffBDiffer",     fg=magenta),               # Binary files differ
    "",

    # ── LSP / Diagnostics (Neovim built-in + older vim-lsp) ────────────
    '" ── LSP / Diagnostics ───────────────────────────────────────────────',
    hi("DiagnosticError",            fg=red_b),      # Error diagnostic text
    hi("DiagnosticWarn",             fg=yellow),      # Warning diagnostic text
    hi("DiagnosticInfo",             fg=blue),        # Info diagnostic text
    hi("DiagnosticHint",             fg=cyan),        # Hint diagnostic text
    hi("DiagnosticUnderlineError",   sp=red_b,   attr="undercurl"),  # Error underline
    hi("DiagnosticUnderlineWarn",    sp=yellow,  attr="undercurl"),  # Warning underline
    hi("DiagnosticUnderlineInfo",    sp=blue,    attr="undercurl"),  # Info underline
    hi("DiagnosticUnderlineHint",    sp=cyan,    attr="undercurl"),  # Hint underline
    # Legacy vim-lsp group aliases
    link("LspDiagnosticsDefaultError",       "DiagnosticError"),
    link("LspDiagnosticsDefaultWarning",     "DiagnosticWarn"),
    link("LspDiagnosticsDefaultInformation", "DiagnosticInfo"),
    link("LspDiagnosticsDefaultHint",        "DiagnosticHint"),
    link("LspDiagnosticsUnderlineError",     "DiagnosticUnderlineError"),
    link("LspDiagnosticsUnderlineWarning",   "DiagnosticUnderlineWarn"),
    link("LspDiagnosticsUnderlineInformation","DiagnosticUnderlineInfo"),
    link("LspDiagnosticsUnderlineHint",      "DiagnosticUnderlineHint"),
    "",

    # ── Git commit & Signify gutter signs ──────────────────────────────
    '" ── Git ─────────────────────────────────────────────────────────────',
    hi("gitcommitSummary",      fg=fg,      attr="bold"),  # First line of commit msg
    hi("gitcommitHeader",       fg=comment),               # Header lines
    hi("gitcommitBranch",       fg=magenta_b, attr="bold"),# Branch name
    hi("gitcommitSelectedType", fg=green),                 # Staged file type
    hi("gitcommitDiscardedType",fg=red),                   # Unstaged file type
    hi("gitcommitSelectedFile", fg=green),                 # Staged filename
    hi("gitcommitUntrackedFile",fg=cyan),                  # Untracked filename
    hi("gitcommitDiff",         fg=comment),               # Inline diff
    link("gitcommitNoBranch",   "gitcommitBranch"),
    hi("SignifySignAdd",    fg=green),                     # Signify: added
    hi("SignifySignChange", fg=yellow),                    # Signify: changed
    hi("SignifySignDelete", fg=red),                       # Signify: deleted
    link("SignifyLineAdd",    "DiffAdd"),
    link("SignifyLineChange", "DiffChange"),
    link("SignifyLineDelete", "DiffDelete"),
    "",

    # ── NERDTree file explorer ─────────────────────────────────────────
    '" ── NERDTree ────────────────────────────────────────────────────────',
    hi("NERDTreeDir",         fg=blue),                # Directory names
    hi("NERDTreeDirSlash",    fg=blue),                # Trailing slash
    hi("NERDTreeFile",        fg=fg),                  # Regular files
    hi("NERDTreeExecFile",    fg=green),               # Executable files
    hi("NERDTreeHelp",        fg=comment),             # Help text
    hi("NERDTreeHelpTitle",   fg=magenta_b, attr="bold"),
    hi("NERDTreeHelpKey",     fg=cyan),                # Keybinding hints
    hi("NERDTreeHelpCommand", fg=yellow),              # Command hints
    hi("NERDTreeUp",          fg=comment),             # ".." entry
    hi("NERDTreeOpenable",    fg=yellow),              # Closed folder marker
    hi("NERDTreeClosable",    fg=yellow),              # Open folder marker
    hi("NERDTreeToggleOn",    fg=green,  attr="bold"), # Toggle on indicator
    hi("NERDTreeToggleOff",   fg=red,    attr="bold"), # Toggle off indicator
    "",

    # ── Startify start screen ──────────────────────────────────────────
    '" ── Startify ────────────────────────────────────────────────────────',
    hi("StartifyHeader",  fg=blue,    attr="bold"),    # Section header
    hi("StartifySection", fg=magenta_b, attr="bold"),  # Section title
    hi("StartifyFile",    fg=fg),                      # File entries
    hi("StartifyPath",    fg=comment),                 # Path portion
    hi("StartifySlash",   fg=comment),                 # Path separators
    hi("StartifyNumber",  fg=yellow),                  # Entry numbers
    hi("StartifyBracket", fg=comment),                 # Brackets around numbers
    hi("StartifySpecial", fg=cyan),                    # Special entries
    "",

    # ── Tagbar tag browser ─────────────────────────────────────────────
    '" ── Tagbar ──────────────────────────────────────────────────────────',
    hi("TagbarKind",       fg=blue,    attr="bold"),   # Tag kind (function, class)
    hi("TagbarSignature",  fg=comment),                # Function signatures
    hi("TagbarHelp",       fg=comment),                # Help text
    hi("TagbarHelpTitle",  fg=magenta_b, attr="bold"), # Help title
    "",

    # ── CoC (Conquer of Completion) ────────────────────────────────────
    '" ── CoC ─────────────────────────────────────────────────────────────',
    hi("CocErrorSign",    fg=red_b),                   # Error sign in gutter
    hi("CocWarningSign",  fg=yellow),                  # Warning sign
    hi("CocInfoSign",     fg=blue),                    # Info sign
    hi("CocHintSign",     fg=cyan),                    # Hint sign
    hi("CocErrorHighlight",   sp=red_b,  attr="undercurl"),  # Error underline
    hi("CocWarningHighlight", sp=yellow, attr="undercurl"),  # Warning underline
    hi("CocInfoHighlight",    sp=blue,   attr="undercurl"),  # Info underline
    hi("CocHintHighlight",    sp=cyan,   attr="undercurl"),  # Hint underline
    hi("CocFloating",     fg=fg,  bg=bg2),             # Floating window
    hi("CocErrorFloat",   fg=red_b,  bg=bg2),         # Error in float
    hi("CocWarningFloat", fg=yellow, bg=bg2),          # Warning in float
    hi("CocInfoFloat",    fg=blue,   bg=bg2),          # Info in float
    hi("CocHintFloat",    fg=cyan,   bg=bg2),          # Hint in float
    "",

    # ── netrw built-in file explorer ───────────────────────────────────
    '" ── netrw ───────────────────────────────────────────────────────────',
    hi("netrwDir",        fg=blue),                    # Directory names
    hi("netrwClassify",   fg=blue),                    # Classification markers
    hi("netrwExe",        fg=green),                   # Executable files
    hi("netrwSuffixes",   fg=comment),                 # File suffixes
    hi("netrwTreeBar",    fg=comment),                 # Tree connector lines
    hi("netrwList",       fg=fg),                      # List entries
    hi("netrwHelpCmd",    fg=cyan),                    # Help commands
    hi("netrwQuickHelp",  fg=comment),                 # Quick help text
    hi("netrwHidePat",    fg=comment),                 # Hidden file patterns
    hi("netrwVersion",    fg=comment),                 # Version string
    "",

    # ── BufTabLine buffer tab bar ──────────────────────────────────────
    '" ── BufTabLine ──────────────────────────────────────────────────────',
    hi("BufTabLineCurrent", fg=fg,      bg=blue, attr="NONE"),  # Active buffer
    hi("BufTabLineActive",  fg=fg,                attr="NONE"), # Visible buffer
    hi("BufTabLineHidden",  fg=comment,           attr="NONE"), # Hidden buffer
    hi("BufTabLineFill",                          attr="NONE"), # Empty tab bar space
    "",

    # ── Terminal colors for embedded :terminal (Vim 8+ / Neovim) ───────
    '" ── Terminal colors (Vim 8+ / Neovim) ───────────────────────────────',
  ]

  # Set g:terminal_color_{0..7} (normal) and {8..15} (bright) so that
  # the embedded terminal inherits the same palette as the editor.
  for i, (normal, bright) in enumerate(palette):
    lines.append("let g:terminal_color_{} = '{}'".format(i, to_hex(normal)))
    lines.append("let g:terminal_color_{} = '{}'".format(i + 8, to_hex(bright)))

  # Create parent directories if they don't exist (e.g. ~/.vim/colors/)
  os.makedirs(os.path.dirname(options.vim_out), exist_ok=True)
  with open(options.vim_out, 'w') as f:
    f.write("\n".join(lines) + "\n")

  # Generate plugin theme files based on --vim-plugins
  plugins = getattr(options, 'vim_plugins', ['airline']) or []
  if 'airline' in plugins:
    _generate_airline(options.vim_out, name, bg, bg2, fg, comment, blue, green, magenta, red)
  if 'nerdtree' in plugins:
    _generate_nerdtree_syntax(options.vim_out, comment, blue, cyan, cyan_b, green, bg2, yellow, yellow_b)


def _generate_airline(vim_out, name, bg, bg2, fg, comment, blue, green, magenta, red):
  """Generate an airline theme file alongside the vim colorscheme."""
  vim_dir = os.path.dirname(os.path.dirname(vim_out))
  airline_dir = os.path.join(vim_dir, 'autoload', 'airline', 'themes')
  os.makedirs(airline_dir, exist_ok=True)
  airline_path = os.path.join(airline_dir, name + '.vim')

  def _al(fg_c, bg_c):
    return "['{fg}', '{bg}', {cfg}, {cbg}]".format(
        fg=to_hex(fg_c), bg=to_hex(bg_c), cfg=to_256(fg_c), cbg=to_256(bg_c))

  al_lines = [
    '" Airline theme generated by iterm-theme-generator',
    "let g:airline#themes#{}#palette = {{}}".format(name),
    "",
    "let s:N1 = {}".format(_al(bg, blue)),
    "let s:N2 = {}".format(_al(fg, bg2)),
    "let s:N3 = {}".format(_al(comment, bg)),
    "let g:airline#themes#{n}#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)".format(n=name),
    "",
    "let s:I1 = {}".format(_al(bg, green)),
    "let s:I2 = {}".format(_al(fg, bg2)),
    "let s:I3 = {}".format(_al(comment, bg)),
    "let g:airline#themes#{n}#palette.insert = airline#themes#generate_color_map(s:I1, s:I2, s:I3)".format(n=name),
    "",
    "let s:V1 = {}".format(_al(bg, magenta)),
    "let s:V2 = {}".format(_al(fg, bg2)),
    "let s:V3 = {}".format(_al(comment, bg)),
    "let g:airline#themes#{n}#palette.visual = airline#themes#generate_color_map(s:V1, s:V2, s:V3)".format(n=name),
    "",
    "let s:R1 = {}".format(_al(bg, red)),
    "let s:R2 = {}".format(_al(fg, bg2)),
    "let s:R3 = {}".format(_al(comment, bg)),
    "let g:airline#themes#{n}#palette.replace = airline#themes#generate_color_map(s:R1, s:R2, s:R3)".format(n=name),
    "",
    "let s:IA = {}".format(_al(comment, bg2)),
    "let g:airline#themes#{n}#palette.inactive = airline#themes#generate_color_map(s:IA, s:IA, s:IA)".format(n=name),
  ]
  with open(airline_path, 'w') as f:
    f.write("\n".join(al_lines) + "\n")


def _generate_nerdtree_syntax(vim_out, comment, blue, cyan, cyan_b, green, bg2, yellow, yellow_b):
  """Generate after/syntax/nerdtree.vim with palette-derived file-type colors."""
  vim_dir = os.path.dirname(os.path.dirname(vim_out))
  nerdtree_dir = os.path.join(vim_dir, 'after', 'syntax')
  os.makedirs(nerdtree_dir, exist_ok=True)
  path = os.path.join(nerdtree_dir, 'nerdtree.vim')

  # Map file types to semantic palette colors
  groups = [
    ('NTShell', comment, r"'\c\zs[^ ].*\.sh'"),
    ('NTMd',    blue,    r"'\c\zs[^ ].*\.md'"),
    ('NTCPPh',  cyan_b,  r"'\c\zs[^ ].*\.\(hpp\|hxx\|h\)'"),
    ('NTCPPs',  cyan,    r"'\c\zs[^ ].*\.\(cpp\|cxx\|c\)'"),
    ('NTPy',    green,   r"'\c\zs[^ ].*\.py'"),
    ('NTPyc',   bg2,     r"'\c\zs[^ ].*\.pyc'"),
    ('NTTxt',   comment, r"'\c\zs[^ ].*\.txt'"),
    ('NTTmp',   bg2,     r"'\c\zs[^ ].*\.tmp'"),
    ('NTMake',  yellow,  r"'\zsMakefile'"),
    ('NTCMake', yellow,  r"'\zsCMakeLists\.txt'"),
    ('NTJson',  yellow_b, r"'\c\zs[^ ].*\.json'"),
  ]

  lines = [
    '" NERDTree file highlighting generated by iterm-theme-generator',
    '',
  ]
  for name, color, _ in groups:
    lines.append('hi {} guifg={}'.format(name, to_hex(color)))
  lines += [
    'hi NERDTreeExecFile guifg=NONE',
    '',
    'call clearmatches()',
    '',
    "let s:tail = '\\ze.\\{-}$'",
    '',
  ]
  for name, _, pat in groups:
    lines.append("call matchadd('{}', {} . s:tail)".format(name, pat))

  with open(path, 'w') as f:
    f.write('\n'.join(lines) + '\n')
